### PR TITLE
hex encoding: Java 11 incompability

### PR DESCRIPTION
**Pull request by 20centaurifux**
As you might have noticed "javax.xml.bind" doesn't exist in Java 11 anymore. This pull request removes the Java specific code and runs faster than the original Clojure function on my system.

I tested the function with 100.000 hex strings from a file. The original code needs 2163 milliseconds on my system. The new function needs only 298 milliseconds.

The test runs fine on my computer. Kindly note that I don't have a ClojureScript environment.

### CODE REVIEW

**Comment by greglook** [comment]
Nice - could you rebase this against `develop` instead of `master` though?

**Comment by greglook** [comment]
Also - for performance evaluation, did you try the existing clojurescript form? The way you have rewritten the code uses lazy sequences, which is going to result in many intermediate sequence allocations. The existing loop version avoids most of this memory churn, and I ran some criterium benchmarks to evaluate. In this snippet, `seq-decode` is the proposed implementation and `loop-decode` is the existing clojurescript version:
```clojure
=> (require '[criterium.core :as crit])

=> (def hex-data (hex/encode (b/random-bytes 64)))

=> (crit/bench (seq-decode hex-data))
Evaluation count : 576000 in 60 samples of 9600 calls.
             Execution time mean : 107.148560 µs
    Execution time std-deviation : 3.884795 µs
   Execution time lower quantile : 103.954975 µs ( 2.5%)
   Execution time upper quantile : 113.313261 µs (97.5%)
                   Overhead used : 8.983197 ns

Found 7 outliers in 60 samples (11.6667 %)
        low-severe       5 (8.3333 %)
        low-mild         2 (3.3333 %)
 Variance from outliers : 22.2547 % Variance is moderately inflated by outliers

=> (crit/bench (loop-decode hex-data))
Evaluation count : 5028000 in 60 samples of 83800 calls.
             Execution time mean : 12.004482 µs
    Execution time std-deviation : 132.569090 ns
   Execution time lower quantile : 11.853618 µs ( 2.5%)
   Execution time upper quantile : 12.312244 µs (97.5%)
                   Overhead used : 8.983197 ns

Found 5 outliers in 60 samples (8.3333 %)
        low-severe       5 (8.3333 %)
 Variance from outliers : 1.6389 % Variance is slightly inflated by outliers
```
It looks like the loop version is about 8x faster than the sequence version, so I'd suggest changing the PR to just remove the reader conditional and `:clj` branch.

**Comment by 20centaurifux** [comment]
Hi, I've tested the loop version on my Linux machine and it's faster than the sequence version. Four days ago I ran the test on a Windows machine with an old JDK (don't know the version, unfortunately). I don't have physical access to the Windows system right now.

You're right, the loop version should be preferred. I didn't find a similar class like DatatypeConverter in the current Java version. I agree that removing the :clj branch is the best way to go.

Thanks for your great feedback :+1:

**Comment by greglook** [comment]
Released 2.0.4 with this fix.

**Pull request closed without merging**
